# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ea30b1894ac26ad5ff7ab71ecc0e441657cd31d0380920031c6f925e4085553074f380d9cd0d947d191d3bd3bc8801ce6dccb70d9df2289f0a0e534db3b4dc2

test:
  secret_key_base: ed93bb63eb543c63659e50dc854fd3e3cb32da86d94e3bf68014fa5eff0cb7416bcc79aaf7ba5dc90caff68f6dc2758582aba9804561e51529ce454d96e36bd0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
